package com.mygdx.game;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;

public class CreatorFiles {
    CreatorFiles(){}
    File file4,file5,file6,file7,file8,file9,file10,file11,file12,file13,file14,file15,file16,file17,file18,file19,file20,file21,file22,file23,file24,fileX1,fileX2,fileX3,fileX4,fileX5,fileX6,fileX7,fileX8,fileX9;
    PrintWriter printWriter4,printWriter5,printWriter6,printWriter7,printWriter8,printWriter9,printWriter11,printWriter12,printWriter13,printWriter14,printWriter15,printWriter16,printWriter17,printWriter18,printWriter19,printWriter20,printWriter21,printWriter22,printWriter23,printWriter24,pX1,pX2,pX3,pX4,pX5,pX6,pX7,pX8,pX9;
    public void create(){
        file4 = new File("/data/data/com.mygdx.game/Health.txt");
        file5 = new File("/data/data/com.mygdx.game/Protection.txt");
        file6 = new File("/data/data/com.mygdx.game/Attack.txt");
        file7 = new File("/data/data/com.mygdx.game/Speed.txt");
        file8 = new File("/data/data/com.mygdx.game/Maneuverability.txt");
        file9 = new File("/data/data/com.mygdx.game/Ore_Elbrium.txt");
        file10 = new File("/data/data/com.mygdx.game/Message.txt");
        file11 = new File("/data/data/com.mygdx.game/Sign.txt");
        file12 = new File("/data/data/com.mygdx.game/CoefficientAttack.txt");
        file13 = new File("/data/data/com.mygdx.game/CoefficientProtection.txt");
        file14 = new File("/data/data/com.mygdx.game/CoefficientSpeed.txt");
        file15 = new File("/data/data/com.mygdx.game/StartChat.txt");
        file16 = new File("/data/data/com.mygdx.game/TrueOrFalse.txt");
        file17 = new File("/data/data/com.mygdx.game/SoundMusic.txt");
        file18 = new File("/data/data/com.mygdx.game/Appearance.txt");
        file19 = new File("/data/data/com.mygdx.game/Leaders.txt");
        file20 = new File("/data/data/com.mygdx.game/LevelBase.txt");
        file21 = new File("/data/data/com.mygdx.game/NameBase.txt");
        file22 = new File("/data/data/com.mygdx.game/HealthBase.txt");
        file23 = new File("/data/data/com.mygdx.game/Villagers.txt");
        file24 = new File("/data/data/com.mygdx.game/Happiness.txt");
        fileX1 = new File("/data/data/com.mygdx.game/TownHall.txt");
        fileX2 = new File("/data/data/com.mygdx.game/WorkShop.txt");
        fileX3 = new File("/data/data/com.mygdx.game/Kitchen.txt");
        fileX4 = new File("/data/data/com.mygdx.game/House.txt");
        fileX5 = new File("/data/data/com.mygdx.game/School.txt");
        fileX6 = new File("/data/data/com.mygdx.game/Factory.txt");
        fileX7 = new File("/data/data/com.mygdx.game/Tower.txt");
        fileX8 = new File("/data/data/com.mygdx.game/Park.txt");
        fileX9 = new File("/data/data/com.mygdx.game/Mill.txt");
        try {
            file4.createNewFile();
            file5.createNewFile();
            file6.createNewFile();
            file7.createNewFile();
            file8.createNewFile();
            file9.createNewFile();
            file10.createNewFile();
            file11.createNewFile();
            file12.createNewFile();
            file13.createNewFile();
            file14.createNewFile();
            file15.createNewFile();
            file16.createNewFile();
            file17.createNewFile();
            file18.createNewFile();
            file19.createNewFile();
            file20.createNewFile();
            file21.createNewFile();
            file22.createNewFile();
            file23.createNewFile();
            file24.createNewFile();
            fileX1.createNewFile();
            fileX2.createNewFile();
            fileX3.createNewFile();
            fileX4.createNewFile();
            fileX5.createNewFile();
            fileX6.createNewFile();
            fileX7.createNewFile();
            fileX8.createNewFile();
            fileX9.createNewFile();
        } catch (IOException e) {
            e.printStackTrace();
        }
            try {
                printWriter4 = new PrintWriter(file4);
                printWriter4.write(String.valueOf(10));
                printWriter4.close();
                printWriter5 = new PrintWriter(file5);
                printWriter5.write(String.valueOf(3));
                printWriter5.close();
                printWriter6 = new PrintWriter(file6);
                printWriter6.write(String.valueOf(3));
                printWriter6.close();
                printWriter7 = new PrintWriter(file7);
                printWriter7.write(String.valueOf(3));
                printWriter7.close();
                printWriter8 = new PrintWriter(file8);
                printWriter8.write(String.valueOf(0));
                printWriter8.close();
                printWriter9 = new PrintWriter(file9);
                printWriter9.write(String.valueOf(0));
                printWriter9.close();
                printWriter11 = new PrintWriter(file11);
                printWriter11.write(String.valueOf(0));
                printWriter11.close();
                printWriter12 = new PrintWriter(file12);
                printWriter12.write(String.valueOf(0));
                printWriter12.close();
                printWriter13 = new PrintWriter(file13);
                printWriter13.write(String.valueOf(0));
                printWriter13.close();
                printWriter14 = new PrintWriter(file14);
                printWriter14.write(String.valueOf(0));
                printWriter14.close();
                printWriter15 = new PrintWriter(file15);
                printWriter15.write(String.valueOf(0));
                printWriter15.close();
                printWriter16 = new PrintWriter(file16);
                printWriter16.write(String.valueOf(0));
                printWriter16.close();
                printWriter17 = new PrintWriter(file17);
                printWriter17.write(String.valueOf(1));
                printWriter17.close();
                printWriter18 = new PrintWriter(file18);
                printWriter18.write(String.valueOf(2));
                printWriter18.close();
                printWriter19 = new PrintWriter(file19);
                printWriter19.write(String.valueOf(0));
                printWriter19.close();
                printWriter20 = new PrintWriter(file20);
                printWriter20.write(0);
                printWriter20.close();
                printWriter21 = new PrintWriter(file21);
                printWriter21.write("");
                printWriter21.close();
                printWriter22 = new PrintWriter(file22);
                printWriter22.write(1);
                printWriter22.close();
                printWriter23 = new PrintWriter(file23);
                printWriter23.write(3);
                printWriter23.close();
                printWriter24 = new PrintWriter(file24);
                printWriter24.write(25);
                printWriter24.close();
                pX1 = new PrintWriter(fileX1);
                pX1.write(1);
                pX1.close();
                pX2 = new PrintWriter(fileX2);
                pX2.write(0);
                pX2.close();
                pX3 = new PrintWriter(fileX3);
                pX3.write(0);
                pX3.close();
                pX4 = new PrintWriter(fileX4);
                pX4.write(0);
                pX4.close();
                pX5 = new PrintWriter(fileX5);
                pX5.write(0);
                pX5.close();
                pX6 = new PrintWriter(fileX6);
                pX6.write(0);
                pX6.close();
                pX7 = new PrintWriter(fileX7);
                pX7.write(0);
                pX7.close();
                pX8 = new PrintWriter(fileX8);
                pX8.write(0);
                pX8.close();
                pX9 = new PrintWriter(fileX9);
                pX9.write(0);
                pX9.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
    }
}